---
title: '0407'
author: "Chia Ning Lee"
date: "2020/4/7"
output: html_document
---

```{r}
vectorsample <- c(2,6,7)
listsample <- list(2,6,7)

print(vectorsample)
print(listsample)
```

```{r}
#用vector 儲存

c("2020-03-31T13:40:55Z",
  "一芳",
  "2杯",
  "水果茶"
)

#用list儲存
`小明交易1` <- list(
  ymd_hms("2020-03-31T13:40:55Z"), # Date/Time class
  "一芳", # character
  2, # numeric
  "水果茶" # character
)
print(`小明交易1`)
```

```{r}
#物件值可以是vector 也可以是list

#以vector的形式儲存資料 並不會被拆開

c(
 c("108學年第1學期","高級會計學","高等統計學"),
 c("108學年第2學期","食在拉丁美洲")
)
```

```{r}
#物件值可以是vector 也可以是list

#以list的形式當成最外層，裡面的元素若是vetcor 可以被拆開

list(
 c("108學年第1學期","高級會計學","高等統計學"),
 c("108學年第2學期","食在拉丁美洲")
)
```

```{r}
# list含兩個vectors
`小明108學年課表A` <- list(
  c("108-1","高級會計學","高等統計學"),
  c("108-2","食在拉丁美洲")
)
print(`小明108學年課表A`)
```

```{r}
# list含兩個lists
`小明108學年課表B` <- list(
  list("108-1","高級會計學","高等統計學"),
  list("108-2","食在拉丁美洲")
)
print(`小明108學年課表B`)
```

```{r}
# list含兩個lists, 子層list又各含兩個vectors
`小明108學年課表C` <- list(
  list(
    c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
  list(
    c("108-2"),
    c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```
```{r}
#list可以命名

`小明108學年課表C` <- list(
  `上學期` = list(
    semester= c("108-1"), # 可只寫 "108-1"
    c("高級會計學","高等統計學")
       ),
    list(
    semester = c("108-2"),
    courses = c("食在拉丁美洲")
  )
)
print(`小明108學年課表C`)
```
##Github commit

```{r}
commit <- list(
  author = c(),
  commiter= list(),
  message=
  
)
```

