---
title: '0410'
author: "Chia Ning Lee"
date: "2020/4/10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
listExample <- 
  list(
    student="小明",
    `學期`=list(
      `108-1`=list(
        list(
          name="個體經濟學",
          teacher="Alice",
          grade=85
        )
      ),
      `108-2`=list(
        list(
          name="總體經濟學",
          teacher="Mark",
          grade=78
        )
      )
    )
  )
# 有多少位置可選：
length(listExample)
```

```{r}
listExample[[1]]
listExample[[2]]
```
```{r}
#台南地圖
library(jsonlite)
fromJSON("https://data.tainan.gov.tw/dataset/4cd9345a-04bf-4328-a97d-314ff78b4763/resource/afc025fc-1ef4-447c-b785-a680391d0ca1/download/tnsport2.json", simplifyDataFrame = F) -> tainanSportsMap
```

```{r}
length(tainanSportsMap)
tainanSportsMap[[58]]
```

```{r}
# 有多少名字可選：
names(listExample)
```

```{r}
listExample$student
listExample$`學期` #特殊字元仍需要用雙引號
#也可以這樣寫
listExample[["student"]]
listExample[["學期"]] #注意學期這邊的不是反頓點 是雙引號
```
```{r}
str(listExample$`學期`)  
str(listExample[["學期"]])
```

```{r}
fromJSON("http://data.ntpc.gov.tw/api/v1/rest/datastore/382000000A-000157-002",
         simplifyDataFrame = F) -> newTaipeiCityVaccine
```

```{r}
str(newTaipeicity)
length(newTaipeiCityVaccine)
names(newTaipeiCityVaccine)
```

```{r}
str(newTaipeiCityVaccine[[1]])
str(newTaipeiCityVaccine$success)
str(newTaipeiCityVaccine[["success"]])

str(newTaipeiCityVaccine[[2]],max.level = 1)
str(newTaipeiCityVaccine$result,max.level = 1)
str(newTaipeiCityVaccine[["result"]],max.level = 1)
```

```{r}
vectorExample <- c("小明","小英","大雄")

# 有多少位置可選：
length(vectorExample)
```

```{r}
#多個元素用一個括號
vectorExample[1]
#重新排列的話用向量的方式
vectorExample[c(3,2,1)]
vectorExample[c(1,3)]
```

```{r}
str(listExample,max.level = 1)
str(listExample[c(1,2)],max.level = 1)
str(listExample[c(2,1)],max.level= 1 )
```
```{r}
#str(tainanSportsMap,max.level = 1)
str(tainanSportsMap[c(1,283,706)],max.level = 1)
```

```{r}
# 顯示到第一層
str(listExample, max.level=1)

listExample[c("學期")] #不建議一個中括號用來選一個
listExample[[c("學期")]]#比較正確的示範
listExample[c("student","學期")]
```

```{r}
fromJSON("https://www.dropbox.com/s/qnm9bnz7vccrvcz/taipeiNightMarkets.json?dl=1", simplifyDataFrame = F) -> taipeiNightMarkets
```

```{r}
str(taipeiNightMarkets[c(1,6)])
str(taipeiNightMarkets[c("寧夏觀光夜市","南機場夜市")])
```
```{r}
vectorExample
vectorExample[c(T,T,F)] # 要，要，不要
```

```{r}
str(listExample)
str(listExample[c(T,F)])
str(listExample[c("student")])
```
```{r}
names(taipeiNightMarkets)
str(taipeiNightMarkets,max.level = 1)
str(taipeiNightMarkets[c(T,F,F,F,T,F,F,F,F,T,F,F,F,T)])
```
```{r}
names(taipeiNightMarkets)
c(T,F,F,
   F,T,F,
   F,F,F,
   T,F,F,
   F,T) ->selectedMarket

taipeiNightMarkets[selectedMarket]
```

```{r}
selectedMarket <- rep(F,14)
selectedMarket[c(1,5,10,14)] <- T

print(selectedMarket)
```

```{r}
str(taipeiNightMarkets[selectedMarket],max.level = 1)
```

```{r}
str(listExample)
```

```{r}
get1 <- listExample[["學期"]] #將listExample裡的“學期”物件值拿出來。
#兩個[[]]叫拿出來

get2 <- listExample["學期"]
#「只留下」listExample裡的“學期”物件值。
#一個中括號[]留下某個物件值
```

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
```

創造出只要“經濟學系”學生的邏輯向量，econOnly。
選出econOnly的names與gender。
在econOnly的gender下創造出只要“F”的邏輯向量, econFemaleOnly。
選出names中為“經濟學系”且“F”的姓名。

```{r}
majors <- c("經濟學系","經濟學系","社會學系","社工系","經濟學系")
names <- c("小英", "小美", "大雄","阿華", "阿尼")
gender <- c("F","F","M","F","M")
c(T,T,F,F,T)-> econ0nly
names[econ0nly]
gender[econ0nly]

#gender[econ0nly][c(1,2)]
c(1,2) ->econFemale0nly
names[econ0nly][econFemale0nly]


```

