---
title: "0520listandpipe"
author: "Chia Ning Lee"
date: "2020/5/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(purrr)
```


```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
  allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
names(example)
```


```{r}
pick_小新 <- example$name == "小新"
data_selected <- 
  list(
    name=example$name[pick_小新],
    weight=example$weight[pick_小新],
    height=example$height[pick_小新],
    hobby=example$hobby[pick_小新],
    residence=example$residence[pick_小新],
    allowance=example$allowance[pick_小新],
    bloodType=example$bloodType[pick_小新]
  )

#data_selected的產生相當於example[[1]][pick_小新]  數字由1-7
```

```{r}
map(example,~.x[pick_小新])->data_selected
data_selected
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/6252gbdnv9owljm/dance.json?dl=1", simplifyDataFrame = F) -> dance
```

```{r}
#第一個dance表演名稱
dance[[1]]$title
#第二個
dance[[2]]$title

```

```{r}
#對dance的每一個元素要取出title
map(dance,~.x$title)->list_titles
View(list_titles)
```

```{r}
#計算每場表演的表演場次 用length()
length(dance[[1]]$showInfo)
length(dance[[2]]$showInfo)

map(dance,~length(.x$showInfo))->  list_numberOfShows 
  
View(list_numberOfShows)
```

```{r}
#找出第4個表演 6個場次的日期與時間
str(dance,max=2)
dance[[4]]$showInfo[[1]]$time
dance[[4]]$showInfo[[2]]$time
```
```{r}
dance[[4]]$showInfo[[2]]$time
map(dance[[4]]$showInfo,~.x$time)->list_showTimes_dance4
View(list_showTimes_dance4)
```

```{r}
#練習
#找出第8個表演的所有場次時間(time)和地點(location):
dance[[8]]$showInfo[[1]]$time

map(dance[[8]]$showInfo,~.x$time)->time08
map(dance[[8]]$showInfo,~.x$location)->location08
```

```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/67BB3C2B-E7D1-43A7-B872-61B2F082E11B?$format=json", simplifyDataFrame = F) ->
  busRoutes

```

```{r}
#練習2
#請抓出每條路線的Id(路線代碼)、providerId(業者代碼)、providerName(業者中文名稱)、nameZh(中文名稱)。
busRoutes[[1]][c("Id","providerId","providerName","nameZh")]
map(busRoutes,~.x[c("Id","providerId","providerName","nameZh")])->bus01
```

```{r}
chr <-c("abaa","accd")
library(stringr)
str_extract_all(chr[[1]],"[ad]")
str_extract_all(chr[[2]],"[ad]")

map(chr,~str_extract_all(.x,"[ad]"))
```
```{r}
jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
```

```{r}
#2.1 找出有氣象預報資訊的縣市名稱（locationName欄位）
weather_next36hours[[1]]$dataset$location$locationName->weathercityname
```

