---
title: '061501'
author: "Chia Ning Lee"
date: "2020/6/15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 先執行此行輸入學號
readline(prompt = "請輸入你的學號") -> studentId 

# 之後才執行以下程式
if(
  str_detect(studentId,'^[43](1[01][0-9]|9[0-9])[0-9]{5}$',negate=T) # condition: 是否輸入學號正確？
) {
  warning("你所輸入的學號不正確")
}
```

```{r}
#practice
readline(prompt="請輸入你的學號")->studentId

library(stringr)
if(
  str_detect(studentId,"^[43](1[01][0-9]|9[0-9])[0-9]{5}$",negate=T)
){
  warning("你所輸入的學號不正確")
  }
```

```{r}
if(!require(lubridate)){ # condition: 是否「沒安裝lubridate」？
  install.packages("lubridate")
}
lubridate::ymd_hms("2020-07-01 13:00:00 GMT")
```

```{r}
#practice
require(lubridate)

if(!require(lubridate)){
  install.packages("lubridate")
}
```

```{r}
convert_TaiwanDate2WesternDate <- function(twDate){
  library(stringr)
  regex_pattern <-
    "(?<=民國)[0-9]+(?=年)"
  
  # 取出民國年，計算西元年
  year <- 
    str_extract(
      twDate,
      regex_pattern)
  westernYear <- as.integer(year)+1911
  
  # 替換民國xx年的xx成西元年數字
  str_replace(
    twDate,
    regex_pattern,  # 要換掉的文字
    as.character(westernYear) # 要替換的內容
  ) -> twDate_reformat
  
  lubridate::ymd(twDate_reformat) -> westernDate
  return(westernDate)
}

twDate <-  c("民國108年12月5日","民國98年10月5日")
convert_TaiwanDate2WesternDate(twDate)
```

```{r}
convert_TaiwanDate2WesternDate <- function(twDate){
  
  if(!require("stringr")){
    install.packages("stringr")
  }
  if(!require("lubridate")){
    install.packages("lubridate")
  }
  
  library(stringr)
  regex_pattern <-
    "(?<=民國)[0-9]+(?=年)"
  
  # 取出民國年，計算西元年
  year <- 
    str_extract(
      twDate,
      regex_pattern)
  westernYear <- as.integer(year)+1911
  
  # 替換民國xx年的xx成西元年數字
  str_replace(
    twDate,
    regex_pattern,  # 要換掉的文字
    as.character(westernYear) # 要替換的內容
  ) -> twDate_reformat
  
  lubridate::ymd(twDate_reformat) -> westernDate
  return(westernDate)
}
```

```{r}
# 檢視步驟耗時elapse time
system.time(
  jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
  weather_next36hours
)
```

```{r}
if(!exists("weather_next36hours")){
    jsonlite::fromJSON("https://opendata.cwb.gov.tw/fileapi/v1/opendataapi/F-C0032-001?Authorization=rdec-key-123-45678-011121314&format=JSON") ->
    weather_next36hours
  print("Not found")
  SOAR::Store(weather_next36hours) # 存在.R_cache environment中
}
```

```{r}
#practice
SOAR::Store(weather_next36hours)
```

```{r}
# n 為偶數
n <- 54
fvalue <- n/2

# n 為奇數
n <- 33
fvalue <- -(n+1)/2
```

```{r}
(n %% 2)==1 # 表示「奇數」; 或...

as.logical(n %% 2) # 只有0會變F，其他數值都是T
```

```{r}
n <- 54
if(as.logical(n %% 2)){
  fvalue <- -(n+1)/2
} else {
  fvalue <- n/2
}
```

```{r}
#practice
n<-54


myfun<-function(n){
  if(as.logical(n%%2)){
  fvalue<- -(n+1)/2
} else{
  fvalue <-n/2
  
}
  return(fvalue)
}
myfun(53)
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/d14j5hp3i5ps657/examSubmissionTimes.json?dl=1") -> examSubmissionTime


head(examSubmissionTime$section)
head(examSubmissionTime$time)
```

```{r}
#沒有分流
i<-1
student_i_section<-examSubmissionTime$section[[i]]
student_i_time <- examSubmissionTime$time[[i]]

deadline<- lubridate::ymd_hms("2020-05-27 15:00:00",tz="Asia/Taipei")

howEarly<-deadline-lubridate::ymd_hms(student_i_time,tz="Asia/Taipei")
print(howEarly)
```

```{r}
#如果有分流的condition設計

i<-1
student_i_section<-examSubmissionTime$section[[i]]
student_i_time <- examSubmissionTime$time[[i]]

if(student_i_section=="56"){
  deadline<- lubridate::ymd_hms("2020-05-27 15:00:00",tz="Asia/Taipei")
}else{
  deadline<- lubridate::ymd_hms("2020-05-27 15:00:00",tz="Asia/Taipei")
}

howEarly<-deadline-lubridate::ymd_hms(student_i_time,tz="Asia/Taipei")
print(howEarly)
```

```{r}
#function＋map算出時間
compute_howEarly<-function(student_i_section,student_i_time){
  if(student_i_section=="56"){
  deadline<- lubridate::ymd_hms("2020-05-27 15:00:00",tz="Asia/Taipei")
}else{
  deadline<- lubridate::ymd_hms("2020-05-27 17:00:00",tz="Asia/Taipei")
}

howEarly<-deadline-lubridate::ymd_hms(student_i_time,tz="Asia/Taipei")
return(howEarly)
}
```

```{r}
compute_howEarly(examSubmissionTime$section[[1]],examSubmissionTime$time[[1]])
compute_howEarly(examSubmissionTime$section[[2]],examSubmissionTime$time[[2]])
compute_howEarly(examSubmissionTime$section[[3]],examSubmissionTime$time[[3]])

```

```{r}
numbar <- 1:length(examSubmissionTime$section)
compute_howEarly(examSubmissionTime$section[[numbar[1]]],examSubmissionTime$time[[numbar[1]]])

purrr::map(numbar,
    ~compute_howEarly(
      examSubmissionTime$section[[.x]],
      examSubmissionTime$time[[.x]])
    )->list_howEarly

list_howEarly
```

```{r}
library(magrittr)
list_howEarly %>%
  unlist()->examSubmissionTime$howEarly

pick_56 <-examSubmissionTime$section=="56"
pick_78 <-examSubmissionTime$section=="78"

mean(examSubmissionTime$howEarly[pick_56])
median(examSubmissionTime$howEarly[pick_56])

mean(examSubmissionTime$howEarly[pick_78])
median(examSubmissionTime$howEarly[pick_78])
```

```{r}
readline("請輸入你的成績（整數）： ") -> grade # 單獨執行
```

```{r}
#practice
readline("請輸入你的成績(整數): ")->grade
```

```{r}
readline("請輸入你的成績(整數): ")->grade
if(grade>=90){
  print("優")
}else if(grade>=80&grade<=89){
  print("良")
}else if(grade>=70&grade<=79){
  print("尚可")
  }else{
    print("待加強")
}
```

