---
title: "20200617 switch"
author: "Chia Ning Lee"
date: "2020/6/27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(magrittr)
library(lubridate)
library(stringr)
library(purrr)
library(glue)

```

```{r}
if (n%%2 == 1){
  fvalue=-(n+1)/2
}else{
  fvalue=n/2
}
```

```{r}
grades <- c(52,77,59,88,90)
ifelse(grades>=60 ,"是","否")
```
```{r}
minifun<- function()lubridate::now()

minifun()

```
```{r}
result<-{
  x<-2
  y<-3
  x**y+15
}

result2 <-{
  x<-5
  y<-3
  if(x<3){
    warning("x值太小")
  }else{
    x**y+15
  }
}
```

```{r}
n<-540

conditionExpression_outcome<-
  ifelse(n%%2==0 ,"even","odd")

switch(
  conditionExpression_outcome,
  "even"={fvalue<-n/2},
  "odd"={fvalue<-(n+1)/2},
  warning("n要整數喔")
)

print(fvalue)
```

```{r}
a<-c(1,2,3)
cut(a,c(1,2,3))
```

```{r}
#大括號裡面如果有指定回傳的話 又要print 就要直接加print
grade<-sample(1:100,10,replace=T)
grade
cut(grade,c(-1,69,79,89,100))->grade

levels(grade)
grade
switch(
  as.character(grade[[9]]),
  "(-1,69]"={
    print("-_-")
    "F"},
  "(69,79]"={
    print("棒")
    "C"
    },
  "(79,89]"={
    print("好棒")
    "B"
    },
  "(89,100]"={
    print("好棒棒")
    "A"
    }
)->letterGrade
```
```{r}
#製作當前時間
library(lubridate)
library(glue)
nowtime <-glue("{today()}18:00:00")%>%ymd_hms(tz="Asia/Taipei")

#製作分割點
cutpoints<-
  c(
    glue("{today()}06:00:00"),
    glue("{today()}09:00:00"),
    glue("{today()}17:00:00"),
    glue("{today()}19:00:00"),
    glue("{today()}23:00:00"),
    glue("{today()+days(1)}01:00:00")
  )
cutpoints%>%
  ymd_hms(tz="Asia/Taipei")->cutpoints

#指定時間會被分到某一個區間
cut(nowtime,cutpoints)->nowtime

levels(nowtime)[c(1,3,5)]<-c("morning","evening","jazz time")

switch(
  as.character(nowtime),
  "morning"={
    print("要不要來讀點國際時事")
    browseURL("https://economist.com")
  },
  "evening"={
    print("需不需要點餐呢？")
    browseURL("https://www.foodpanda.com.tw/")
  },
  "jazz time"={
    print("放鬆聽點Jazz。")
    browseURL("https://open.spotify.com/playlist/37i9dQZF1DXbITWG1ZJKYt")
  },
  {print("機器人要休息，饒了我吧~~")}
)
```

```{r}
whatNeedToDo_butler_mom <- function(nowtime=now()){
  
library(lubridate)
library(glue)

#製作分割點
cutpoints<-
  c(
    glue("{today()}06:00:00"),
    glue("{today()}09:00:00"),
    glue("{today()}17:00:00"),
    glue("{today()}19:00:00"),
    glue("{today()}23:00:00"),
    glue("{today()+days(1)}01:00:00")
  )
cutpoints%>%
  ymd_hms(tz="Asia/Taipei")->cutpoints

#指定時間會被分到某一個區間
cut(nowtime,cutpoints)->nowtime

levels(nowtime)[c(1,3,5)]<-c("morning","evening","jazz time")

switch(
  as.character(nowtime),
  "morning"={
    print("要不要來讀點國際時事")
    browseURL("https://economist.com")
  },
  "evening"={
    print("需不需要點餐呢？")
    browseURL("https://www.foodpanda.com.tw/")
  },
  "jazz time"={
    print("放鬆聽點Jazz。")
    browseURL("https://open.spotify.com/playlist/37i9dQZF1DXbITWG1ZJKYt")
  },
  {
    print("機器人要休息，饒了我吧~~")
  }
 )
}

ymd_hms(glue::glue("{today()} 08:00:00"),tz="Asia/Taipei") %>%
  whatNeedToDo_butler_mom()

```
```{r}
myAnswer <- c(2,3,6)
correctAnswer <- c(2,3,5)

if(any(myAnswer==correctAnswer)){
  print("恭喜你答對了")
}

#可以使用any或all來解決重複的問題

```

