---
title: '20200504'
author: "Chia Ning Lee"
date: "2020/5/4"
output: html_document
---
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
a <- c(2, 3, 5)
b <- c(4,-1, 3)
```

```{r}
a+b
a-b
a*b
a/b
```
```{r}
a%%b
c(2%%4,3%%-1,5%%3)
```

```{r}
a %% b
# 相當於
c(2%%4, 3%%(-1), 5%%3)

a ** b
```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
print(sequenceNums)

sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數
```

```{r}
5*c(1,3,4)+7
# 其實是
c(5)*c(1,3,4)+c(7)

## 對向量5，向量7進行recycle:
c(5,5,5)*c(1,3,4)+c(7,7,7)
## Recycle等長後才進行elementwise operation:
c(5*1+7, 5*3+7, 5*4+7)
```

```{r}
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)
```

```{r}
# 狀況二: 倍數堆疊一定會超過，只好截斷
c(2,3)/c(-2,-13,10)
c(2,3,2)/c(-2,-13,10)
```

```{r}
paste0(
  c("我叫"),c("小明","小美")
)
#等同於
paste0(
  c("我叫","我叫"),c("小明","小美")
)
```
```{r}
paste0(
  c("他叫","我叫"),c("小明","小美","大雄")
)
```

```{r}
example <- list(
  name=c("小明","小花","小新","美美"),
  height=c(175,166,170,160),
  weight=c(77,NA,60,43),
  birthday=lubridate::ymd(c("1998-03-11","1999-12-22","1995-08-22","2001-10-10")),
  hobby=c("美食 旅遊","旅遊 時尚","3C 美食","音樂 旅遊"),
  residence=c("Taipei","New Taipei","Taichung","Kaohsiung"),
```


```{r}
allowance=factor(c("0-1000","1001-2000","2000+","1001-2000")),
  bloodType=c("A","B","B","O")
)
```

```{r}
str(example[c("name","height")])

pickabove_170 <- example$height >=170
example$height >=170
example$name[pickabove_170]
```
```{r}
source("https://www.dropbox.com/s/qsrw069n94k61lj/transcript100to103_list.R?dl=1")
```

```{r}
str(transcript100to103)
```

```{r}
#各學屆2年級人數
table(transcript100to103$`學屆`)
#選出二年級成績大於85的
pickabove_85 <- transcript100to103$`成績` >85
table(transcript100to103$`學屆`[pickabove_85])

```
```{r}
example$birthday
class(example$birthday)
typeof(example$birthday)
```

```{r}
print(example[c("name","birthday")])

pick_after98 <- example$birthday >= lubridate::ymd("1998-01-01")
example$name[pick_after98]
```
```{r}
source("https://www.dropbox.com/s/16h6ggua6qtydci/exchangeRate.R?dl=1")
```

```{r}
str(exchangeRate)
```



```{r}
library(lubridate)
pick_after98_01 <- exchangeRate$`期間` >= ymd("1998-01-01")
```

```{r}
#留下98年以後的資料
exchangeRate_after98 <-list(
  `期間`=exchangeRate$`期間`[pick_after98_01],
  `幣別`=exchangeRate$`幣別`[pick_after98_01],
  `匯率`=exchangeRate$`匯率`[pick_after98_01]
  
)
```

```{r}
#可排序類別資料比較
print(example[c("name","allowance")])
```
```{r}
levels(example$allowance)
```

```{r}
example$allowance <-
  ordered(example$allowance)
```

```{r}
class(example$allowance)
```

```{r}
pick_allowanceover1000 <-
  example$allowance >=  "1001-2000"
example$name[pick_allowanceover1000]
```
```{r}
#也可以在原始資料就做處理
example$allowance <-factor(
  c("0-1000","1001-2000", "2000+","1001-2000"),
  levels=c("0-1000","1001-2000", "2000+"),#設定level的呈現
  ordered = T #設定為可排序factor
)
```

```{r}
jsonlite::fromJSON("https://www.dropbox.com/s/3uijub7xheib405/list_victimAges_female.json?dl=1", simplifyDataFrame = F) -> list_victimAges_female
```

```{r}
list_victimAges_female
View(list_victimAges_female$`數目`)
sum(list_victimAges_female$`數目`,na.rm=T)
```

```{r}
print(example[c("name","bloodtype")])
pick_bloodb<- example$bloodType =="B"
example$name[pick_bloodb]
```

```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
#創造可留下偶數的「要/不要」向量pick_evens。

pick_evens <- (sequenceNums%%2) == 0
sequenceNums[pick_evens]
```

```{r}
x <- c(1,5,8)
y <- c(5,8)

# x裡的元素值是不是屬於y集合
x %in% y
```

```{r}
#example中誰來自大台北
example[c("name","residence")]
set_Taipeimetro <- c("Taipei","New Taipei")
pickfrom_TaipeiMetro <-
  example$residence %in% set_Taipeimetro
example$name[pickfrom_TaipeiMetro]
```

```{r}
str(transcript100to103)
```
```{r}
#創造 可選出來自法商學院的「要/不要」向量，pick_lawBusiness。
str(transcript100to103)
levels(factor(transcript100to103$`學院`))
unique(transcript100to103$`學院`)
lawBusiness <- c("法學院","商學院")
pick_lawBusiness <- 
  transcript100to103$`學院`%in% lawBusiness

```

```{r}
pick_not_fromTaipeiMetro <- ! pick_fromTaipeiMetro
# 或
pick_not_fromTaipeiMetro <- !(example$residence %in% set_TaipeiMetro) # (..) 裡面會先運算完才做外面!的處理
```

```{r}
x2 <- c(1,NA,10)
y2 <- c(-1,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")
```

```{r}
is.na(x2)
```

```{r}
print(example[c("name","weight")])

pick_na <- is.na(example$weight)
example$name[pick_na]
```
```{r}
str(list_victimAges_female)
```

```{r}
list_victimAges_female$`數目` <- as.integer(list_victimAges_female$`數目`)
```

```{r}
pick_na <- is.na(list_victimAges_female$`數目`)
total_na <- sum(pick_na)
total_na
```

```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
example$name[pick_loveFood]
```

```{r}
print(example[c("name","hobby")])

pick_loveFood <- stringr::str_detect(example$hobby,"美食")
example$name[pick_loveFood]
```

```{r}
jsonlite::fromJSON("https://data.ntpc.gov.tw/od/data/api/EDC3AD26-8AE7-4916-A00B-BC6048D19BF8?$format=json") ->
  garbageRoutes
```

```{r}
#  1 用typeof()函數查詢電腦實質上如何看待garbageRoutes。
typeof(garbageRoutes)  
#  2 用class()函數查詢電腦把它能進行的操作運算歸屬於哪一類型。
class(garbageRoutes)
```
```{r}
factor(garbageRoutes$linename) ->garbageRoutes$linename
levels(garbageRoutes$linename)
# 由linename創造： 可篩選出下午路線的「要/不要」向量pick_afternoonRoutes。
pick_afternoonRoutes <-
  stringr::str_detect(garbageRoutes$linename,"下午")
garbageRoutes$linename[pick_afternoonRoutes]
```
```{r}
library(stringr)
fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "a")
str_detect(fruit, "^a")  #找出以a的字元為開頭的
str_detect(fruit, "a$") #找出以a的字元為結尾的
str_detect(fruit, "b")
str_detect(fruit, "[aeiou]")

# Also vectorised over pattern
str_detect("aecfg", letters)

# Returns TRUE if the pattern do NOT match
str_detect(fruit, "^p", negate = TRUE)
#negate=T 會讓這些東西自然反向 True變成False False變TRUE
#但也可以直接加驚嘆號
```

```{r}
CDC_chatbox <- readr::read_csv("http://od.cdc.gov.tw/pr/CDC_chatbox.csv")
```
```{r}
pneumonia <- 
  str_detect(CDC_chatbox$Question,"肺炎")
CDC_chatbox$Question[pneumonia]

```

