---
title: "R"
author: "Chia Ning Lee"
date: "2020/3/18"
output: html_document
---

```{r}
a <-2
3 ->b
```

```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15 #用點開頭的不太會出現在旁邊的參數中
```



```{r}
a<-5
a2<-5L
```

```{r}
class(a)
class(a2)
```

```{r}
aVector <- c(5,6,7)
a2Vector <- c(5L,6L,7L)
class(aVector)
class(a2Vector)
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 
```

```{r}
dialogue <- c("小明說：'明天不用上課。'",
               "小花說：'真的嗎？'")

cat(dialogue, sep="\n")
```

```{r}
alogical <- c(TRUE,T,F,FALSE)
sum(alogical)
```

```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
```{r}


majors10_factor <- factor(
  c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
)

typeof(majors10_factor)
class(majors10_factor)
```

```{r}
majors10_char
majors10_factor
```

```{r}
levels(majors10_factor)
```

```{r}
majors10_factor
```

```{r}
as.integer(majors10_factor)
```
```{r}
Birthplace <-factor(
c('台北市','高雄市','台中市','高雄市','台北市')
)
```

```{r}
typeof(Birthplace)
class(Birthplace)
as.integer(Birthplace)
levels(Birthplace)
Birthplace
```

```{r}
studentId <- c(410773002, 410773015)
class(studentId)
```

```{r}
vnumcomplex <- c(c(1,3,c(-5,23)))
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c()
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1)
```

##different types
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```

```{r}
typeof(num2Vector)
class(num2Vector)
```

```{r}
Hesaid <- "他說:\"今天多了一個確診。\""
#\符號代表escape
```

